stickers:
  today: 5
  recur: 1

history:
  today: 10
  recur: 5

shirt_codeday:
  today: 20
  recur: 7
  options:
    - S
    - M
    - L

hoodie_black:
  today: 75
  recur: 25
  options:
    - XS
    - S
    - M
    - L
    - XL
